# Preface {.unnumbered}


Welcome to the module MA32011 Dynamical systems.

My name is Philip Murray and I am the module lead.

## How to contact me?

* email: pmurray@dundee.ac.uk
* office: G11, Fulton Building
* Teams: PM me


## Lecture notes
You can find lecture notes for the module on this page. If you would like a pdf this can be easily generated by clicking on the pdf link of the  webpage. I will occasionally edit/update the notes as we proceed through lectures. If you spot any errors, typos or omissions please let me know.

## Reading 

Nonlinear dynamics and chaos, Steven Strogatz @strogatz2001nonlinear
Mathematical Biology I, @murray2002mathematical


## Python codes

I have provided Python codes for most of the figures in the notes (you can unfold code section by clicking `Code'). Note that the Python code does not appear in the pdf.

Many of you have taken the Introduction to Programming module at Level 2 and have therefore some experience using Python. I strongly encourage you to use the provided codes as a tool to play around with numerical solutions of the various models that we will be working on. The codes should run as standalone Python codes.


::: {.callout-note}

To access Python on  Uni machines:

1. Launch Anaconda from AppsAnywhere
2. When a folder opens, double click on *Spyder*.
3. Paste a code from lecture notes into the editor on the left-hand side.
4. Click on the green arrow to run the code.
5. The plots should appear in the plots tab on the right-hand side.
6. Experiment with the code. When you change a model parameter, does the solution change in an expected way?

:::

 I have also provided some examples of how to use Python as a symbolic calculator. This uses a Python library called *sympy* and is quite similar to Maple. 

## Assessment
 
* Final exam (80 \%)

* 2 class tests (8 \% each), Week 7 and 11

* 4 quizes (1 \% each), Week 2,4,6 and 9

## Plan

| Week | Up to Section | Tutorial sheet| Assessment |
|-------|:---|-----| ---|
| 1     |   |   1 |  |
| 2     |   |   1 | Quiz 1|
| 3     |   |   2 |        |
| 4     | 3.4  |   2 | Quiz 2  |
| 5     |   |   3 |
| 6     |   |   3 | Quiz 3|
| 7     |   |   4 | Test 1|
| 8     |   |   4 | |
| 9     |   |   5 | Quiz 4 4|
| 10    |   |   5 | |
| 11    |   |  Test 2  |
: Projected delivery

## References
